[package]
name = "fastxt_desktop"
version = "0.1.0"
edition = "2024"
authors = ["Ares <ttenx@pm.me>"]

[[bin]]
name = "fastxt"
path = "src/bin/main.rs"

[features]
default = []
ai = ["fastxt_core/ai"]

[dependencies]
fastxt_core = { path = "../fastxt_core" }
serde_json = "1"
tokio = { version = "1", features = ["rt-multi-thread"] }
iced = { version = "0.14", features = ["qr_code", "tokio"] }
