[package]
name = "fastxt_cli"
version = "0.2.0"
authors = ["Yi Wang"]
license = "AGPL-3.0"
edition = "2024"

[dependencies.fastxt_core]
path = "../fastxt_core"

[dependencies]
clap = { version = "4", features = ["derive"] }
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
ctrlc = "3"

[[bin]]
name = "fastxt-server"
path = "src/bin/fastxt-server.rs"

[[bin]]
name = "fastxt-sync"
path = "src/bin/fastxt-sync.rs"
