/*
    Fastxt
    Copyright (C) 2018-2019  Yi Wang

    This program is free software: you can redistribute it and/or modify
    it under the terms of the GNU Affero General Public License as published by
    the Free Software Foundation, either version 3 of the License, or
    (at your option) any later version.

    This program is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU Affero General Public License for more details.

    You should have received a copy of the GNU Affero General Public License
    along with this program.  If not, see <https://www.gnu.org/licenses/>.
*/

use super::Fastxt;
use crate::exe::get_sqlite_connection;
use crate::upgrade::get_meta_version;
use futures::{
    future::{self, Ready},
    prelude::*,
};
use std::process;
use std::{io, net::SocketAddr};
use tarpc::{
    context,
    server::{self, Channel, Handler},
};
use tokio::runtime::Runtime;
use tokio_serde::formats::Json;

#[derive(Clone)]
struct FastxtServer(SocketAddr);

impl Fastxt for FastxtServer {
    type IsVersionMatchFut = Ready<bool>;
    fn is_version_match(self, _: context::Context, version: String) -> Self::IsVersionMatchFut {
        let conn = get_sqlite_connection();
        if version == get_meta_version(&conn) {
            future::ready(true)
        } else {
            future::ready(false)
        }
    }
    type StopFut = Ready<bool>;
    fn stop(self, _: context::Context) -> Self::StopFut {
        eprintln!("server stopping");
        process::exit(0);
        future::ready(true)
    }
}

async fn start_server(addr: &SocketAddr) -> io::Result<()> {
    tarpc::serde_transport::tcp::listen(addr, Json::default)
        .await?
        // Ignore accept errors.
        .filter_map(|r| future::ready(r.ok()))
        .map(server::BaseChannel::with_defaults)
        // Limit channels to 1 per IP.
        .max_channels_per_key(1, |t| t.as_ref().peer_addr().unwrap().ip())
        // serve is generated by the service attribute. It takes as input any type implementing
        // the generated World trait.
        .map(|channel| {
            let server = FastxtServer(channel.as_ref().as_ref().peer_addr().unwrap());
            channel.respond_with(server.serve()).execute()
        })
        // Max 10 channels.
        .buffer_unordered(10)
        .for_each(|_| async {})
        .await;

    Ok(())
}

pub fn start(addr: &str) -> Result<(), &'static str> {
    let server_addr: SocketAddr = addr
        .parse()
        .unwrap_or_else(|e| panic!(r#"server_addr {} invalid: {}"#, addr, e));
    let mut rt = Runtime::new().unwrap();
    rt.block_on(async {
        start_server(&server_addr).await;
    });
    Ok(())
}
